steps:
# Clone the repo only if not rolling back
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    if [ -z "${_ROLLBACK_VERSION}" ]; then
      git clone https://github.com/sraghavendrak/cicd-repo5;
    fi

# Build the Docker image only if not rolling back
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    if [ -z "${_ROLLBACK_VERSION}" ]; then
      docker build -t gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION} .;
    fi

# Push the Docker image only if not rolling back
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    if [ -z "${_ROLLBACK_VERSION}" ]; then
      docker push gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION};
    fi

# Deploy the new image or rollback to a previous image
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    if [ -z "${_ROLLBACK_VERSION}" ]; then
      kubectl set image deployment/cicd-app-1 runimage-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION};
    else
      kubectl set image deployment/cicd-app-1 runimage-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_ROLLBACK_VERSION};
    fi
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'

substitutions:
  _PROJECT_ID : gcp-devops-432119
  _CINAME : gke-image
  _VERSION : v5.0
  _ROLLBACK_VERSION : ''  # Set this to the version you want to rollback to

options:
  logging : CLOUD_LOGGING_ONLY
